import 'package:hive/hive.dart';
// part 'news.g.dart'; // This will be generated by Hive

@HiveType(typeId: 0)
class News {
  @HiveField(0)
  String? figCaption;
  @HiveField(1)
  String? summarized;
  @HiveField(2)
  String? summarizedTitle;
  @HiveField(3)
  String? author;
  @HiveField(4)
  String? source;
  @HiveField(5)
  String? sourcename;
  @HiveField(6)
  String? sourceimage;
  @HiveField(7)
  List<ImageModel> mainImages;
  @HiveField(8)
  String time;
  @HiveField(9)
  String id;
  @HiveField(10)
  String? publishedDate;
  @HiveField(11)
  String? audio;
  @HiveField(12)
  int likeCount;
  @HiveField(13)
  List<Comment> comments;

  News({
    required this.author,
    required this.mainImages,
    required this.time,
    required this.id,
    this.figCaption,
    this.summarized,
    this.summarizedTitle,
    this.source,
    this.sourcename,
    this.sourceimage,
    this.publishedDate,
    this.audio,
    this.likeCount = 0,
    this.comments = const [],
  });

  Map<String, dynamic> toJson() {
    return {
      'figCaption': figCaption,
      'summarized': summarized,
      'summarizedTitle': summarizedTitle,
      'author': author,
      'source': source,
      'sourcename': sourcename,
      'sourceimage': sourceimage,
      'mainImages': mainImages.map((image) => image.toJson()).toList(),
      'time': time,
      'id': id,
      'publishedDate': publishedDate,
      'audio': audio,
      'likeCount': likeCount,
      'comments': comments.map((comment) => comment.toJson()).toList(),
    };
  }

  factory News.fromJson(Map<String, dynamic> json) {
    return News(
      figCaption: json['figCaption'],
      summarized: json['summarized'],
      summarizedTitle: json['summarizedTitle'],
      author: json['author'],
      source: json['source'],
      sourcename: json['sourcename'],
      sourceimage: json['sourceimage'],
      mainImages: (json['mainImages'] as List<dynamic>)
          .map((imageJson) => ImageModel.fromJson(imageJson))
          .toList(),
      time: json['time'],
      id: json['id'],
      publishedDate: json['publishedDate'],
      audio: json['audio'],
      likeCount: json['likeCount'] ?? 0,
      comments: (json['comments'] as List<dynamic>?)
              ?.map((commentJson) => Comment.fromJson(commentJson))
              .toList() ??
          [],
    );
  }
}

@HiveType(typeId: 1)
class ImageModel {
  @HiveField(0)
  String url;
  @HiveField(1)
  String caption;

  ImageModel({
    required this.url,
    required this.caption,
  });

  factory ImageModel.fromJson(Map<String, dynamic> json) {
    return ImageModel(
      url: json['url'],
      caption: json['caption'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'url': url,
      'caption': caption,
    };
  }
}

@HiveType(typeId: 2)
class Comment {
  @HiveField(0)
  String id;
  @HiveField(1)
  String text;
  @HiveField(2)
  String userId;
  @HiveField(3)
  String username;
  @HiveField(4)
  DateTime timestamp;

  Comment({
    required this.id,
    required this.text,
    required this.userId,
    required this.username,
    required this.timestamp,
  });

  factory Comment.fromJson(Map<String, dynamic> json) {
    return Comment(
      id: json['id'],
      text: json['text'],
      userId: json['userId'],
      username: json['username'],
      timestamp: DateTime.parse(json['timestamp']),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'text': text,
      'userId': userId,
      'username': username,
      'timestamp': timestamp.toIso8601String(),
    };
  }
}
