import 'package:flutter/material.dart';

import '../../localization/demo_localization.dart';

List<Map<String, String>> leagues = [
  {'name': 'የእንግሊዝ\nፕሪምየር ሊግ', 'id': '39'},
  {'name': 'የአውሮፓ\nሻምፒዮንስ ሊግ', 'id': '2'},
  {'name': 'የኢትዮጵያ\nፕሪምየር ሊግ', 'id': '363'},
  {'name': 'የስፔን\nላሊጋ', 'id': '140'},
  {'name': 'ፈረንሳይ\nሊግ 1', 'id': '61'},
  {'name': 'የጣሊያን\nሴሪያ', 'id': '135'},
  {'name': 'ቡንደስ\nሊጋ', 'id': '78'},
  {'name': 'የአውሮፓ\nሊግ', 'id': '3'},
  {'name': 'የሳዑዲ\nፕሮ ሊግ', 'id': '307'},
  {'name': 'ኤፍ ኤ\nዋንጫ', 'id': '45'},
  {'name': 'ካራባኦ\nEFL', 'id': '48'},
  {'name': 'እንግሊዝ\nሊግ 1', 'id': '41'},
  {'name': 'እንግሊዝሊግ 2', 'id': '42'},
  {'name': 'እንግሊዝ\nሻምፒዮንስ ሺፕ', 'id': '40'},
  {'name': 'የቱርክ\nሱፐር ሊግ', 'id': '203'},
  {'name': 'የግብጽ \n ፕሪምየር ሊግ ', 'id': '233'},
  {'name': 'ደቡብ አፍሪካ\n ፕሪሚየር', 'id': '288'},
  {'name': 'ሜጀር ሊግ\n ሶከር', 'id': '253'},
  {'name': 'ኔዘርላንድ\n ኤርዴቪስ ', 'id': '88'},
  {'name': 'ቤልጅየም\n ፕሮ ሊግ', 'id': '144'},
  {'name': 'ኳታር\n ስታርስ ሊግ ', 'id': '305'},
  {'name': 'ፖርቹጋል \n ፕሪምየራ ሊጋ ', 'id': '94'},
  {'name': 'ስኮትላንድ\n ፕሪሚየርሺፕ', 'id': '179'},
  {'name': 'የአፍሪካ ዋንጫ', 'id': '6'},
  {'name': 'የአውሮፓ ዋንጫ', 'id': '4'},
  {'name': 'የአውሮፓ\nኔሽንስ ሊግ', 'id': '5'},
  {'name': 'ኮፓ አሜሪካ', 'id': '9'},
  {'name': 'ኦሎምፒክስ\nወንዶች', 'id': '480'},
  {'name': 'የዓለም\nዋንጫ', 'id': '1'},
];

List<String> shortLeagueNames = [
  DemoLocalizations.all,
  'ፕሪምየር ሊግ',
  'ሻምፒዮንስ ሊግ',
  'የኢትዮጵያ ፕሪምየር ሊግ',
  'ላሊጋ',
  'ሊግ 1',
  'ሴሪያ',
  'ቡንደስ ሊጋ',
  'የአውሮፓ ሊግ',
  'የሳዑዲ ፕሮ ሊግ',
  'ኤፍ ኤ ካፕ',
  'ካራባኦ EFL',
];

List<String> leaguePics = [
  'english',
  'uefa',
  'eth_league',
  'laliga',
  'league1',
  'seria',
  'bundes',
  'europa',
  'pro_league',
  'fa',
  'carabao',
  'efl_league_one',
  'efl_league_two',
  'efl_championsship',
  'turk',
  'egypt',
  'premier_soccer_league', //southafrica
  'MajorLeagueSoccer(MLS)',
  'netherland',
  'belgium',
  'Qatar',
  'premiera', //portugal
  'premiership', //scotland
  'africa',
  'europe',
  'nations_league',
  'CopaAmerica',
  'olympic',
  'fifa',
  'fifa',
  'fifa',
  'fifa',
  'fifa',
  'fifa'
];

List<int> leagueids = [
  39,
  2,
  363,
  140,
  61,
  135,
  78,
  3,
  307,
  45,
  48,
  41,
  42,
  40,
  203,
  233,
  288,
  253,
  88,
  144,
  305,
  94,
  179,
  6,
  4,
  5,
  9,
  480,
  32,
  29,
  34,
  31,
  30,
  33,
];
List<IconData> icons = [
  Icons.home,
  Icons.explore,
  Icons.search,
  Icons.feed,
  Icons.post_add,
  Icons.local_activity,
  Icons.settings,
  Icons.person
];
List<int> leagueidsForMatches = [
  0,
  39,
  2,
  363,
  140,
  61,
  135,
  78,
  3,
  307,
  45,
  48,
  41,
  42,
  40,
  203,
  233,
  288,
  253,
  88,
  144,
  305,
  94,
  179,
  6,
  4,
  5,
  9,
  480,
  32,
  29,
  34,
  31,
  30,
  33,
];

const List<String> _leagueLocalizationKeys = [
  'premier_league',
  'champions_league',
  'ethiopian_premier_league',
  'la_liga',
  'ligue_1',
  'serie_a',
  'bundesliga',
  'europa_league',
  'saudi_pro_league',
  'fa_cup',
  'carabao_efl',
  'english_league_one',
  'english_league_two',
  'english_champions_ship',
  'turkey_lig_1',
  'egypt_premier_league',
  'south_africa_premier_soccer_league',
  'MLS',
  'netherland_erdivisie',
  'belgium_jupiler_pro_league',
  'qatar_stars_league',
  'portugal_primeira_liga',
  'scotland_premiership',
  'african_cup',
  'european_cup',
  'european_nations_league',
  'copa_america',
  'olympicsmen',
  'wc_qualification',
];

const List<String> _leagueEnglishFallback = [
  'Premier League',
  'Champions League',
  'Ethiopian Premier League',
  'La Liga',
  'Ligue 1',
  'Serie A',
  'Bundesliga',
  'Europa League',
  'Saudi Pro League',
  'FA Cup',
  'Carabao Cup',
  'EFL League One',
  'EFL League Two',
  'EFL Championship',
  'Turkish Lig 1',
  'Egypt Premier League',
  'South Africa Premier Soccer League',
  'MLS',
  'Eredivisie',
  'Belgian Jupiler Pro League',
  'Qatar Stars League',
  'Primeira Liga',
  'Scottish Premiership',
  'African Cup',
  'European Cup',
  'European Nations League',
  'Copa America',
  'Olympics Men',
  'World Cup Qualification',
];

List<String> getLocalizedLeagueNames() {
  return [
    DemoLocalizations.premierLeague,
    DemoLocalizations.championsLeague,
    DemoLocalizations.ethiopianPremierLeague,
    DemoLocalizations.laLiga,
    DemoLocalizations.ligue1,
    DemoLocalizations.serieA,
    DemoLocalizations.bundesliga,
    DemoLocalizations.europaLeague,
    DemoLocalizations.saudiProLeague,
    DemoLocalizations.faCup,
    DemoLocalizations.carabaoEFL,
    DemoLocalizations.englishLeagueOne,
    DemoLocalizations.englishLeagueTwo,
    DemoLocalizations.englishChampionsShip,
    DemoLocalizations.turkeyLig1,
    DemoLocalizations.egyptPremierLeague,
    DemoLocalizations.southAfricaPremierSoccerLeague,
    DemoLocalizations.MLS,
    DemoLocalizations.netherlandEredivisie,
    DemoLocalizations.belgiumJupilerProLeague,
    DemoLocalizations.qatarStarsLeague,
    DemoLocalizations.portugalPrimeiraLiga,
    DemoLocalizations.scotlandPremiership,
    DemoLocalizations.africanCup,
    DemoLocalizations.europeanCup,
    DemoLocalizations.europeanNationsLeague,
    DemoLocalizations.copaAmerica,
    DemoLocalizations.olympicsmen,
    DemoLocalizations.wcQualification,
  ];
}

String leagueNameForIndex(int index) {
  if (index < 0 || index >= _leagueLocalizationKeys.length) {
    return '';
  }

  final key = _leagueLocalizationKeys[index];
  final englishName = DemoLocalizations.getLocalizedValue('en', key).trim();
  if (englishName.isNotEmpty) {
    return englishName;
  }

  if (index < _leagueEnglishFallback.length) {
    return _leagueEnglishFallback[index];
  }

  return '';
}

String content = 'standing';
