import 'package:flutter/material.dart';

import '../../localization/demo_localization.dart';

List<Map<String, String>> leagues = [
  {'name': 'የእንግሊዝ\nፕሪምየር ሊግ', 'id': '39'},
  {'name': 'የአውሮፓ\nሻምፒዮንስ ሊግ', 'id': '2'},
  {'name': 'የኢትዮጵያ\nፕሪምየር ሊግ', 'id': '363'},
  {'name': 'የስፔን\nላሊጋ', 'id': '140'},
  {'name': 'ፈረንሳይ\nሊግ 1', 'id': '61'},
  {'name': 'የጣሊያን\nሴሪያ', 'id': '135'},
  {'name': 'ቡንደስ\nሊጋ', 'id': '78'},
  {'name': 'የአውሮፓ\nሊግ', 'id': '3'},
  {'name': 'የሳዑዲ\nፕሮ ሊግ', 'id': '307'},
  {'name': 'ኤፍ ኤ\nዋንጫ', 'id': '45'},
  {'name': 'ካራባኦ\nEFL', 'id': '48'},
  {'name': 'እንግሊዝ\nሊግ 1', 'id': '41'},
  {'name': 'እንግሊዝሊግ 2', 'id': '42'},
  {'name': 'እንግሊዝ\nሻምፒዮንስ ሺፕ', 'id': '40'},
  {'name': 'የቱርክ\nሱፐር ሊግ', 'id': '203'},
  {'name': 'የግብጽ \n ፕሪምየር ሊግ ', 'id': '233'},
  {'name': 'ደቡብ አፍሪካ\n ፕሪሚየር', 'id': '288'},
  {'name': 'ሜጀር ሊግ\n ሶከር', 'id': '253'},
  {'name': 'ኔዘርላንድ\n ኤርዴቪስ ', 'id': '88'},
  {'name': 'ቤልጅየም\n ፕሮ ሊግ', 'id': '144'},
  {'name': 'ኳታር\n ስታርስ ሊግ ', 'id': '305'},
  {'name': 'ፖርቹጋል \n ፕሪምየራ ሊጋ ', 'id': '94'},
  {'name': 'ስኮትላንድ\n ፕሪሚየርሺፕ', 'id': '179'},
  {'name': 'የአፍሪካ ዋንጫ', 'id': '6'},
  {'name': 'የአውሮፓ ዋንጫ', 'id': '4'},
  {'name': 'የአውሮፓ\nኔሽንስ ሊግ', 'id': '5'},
  {'name': 'ኮፓ አሜሪካ', 'id': '9'},
  {'name': 'ኦሎምፒክስ\nወንዶች', 'id': '480'},
  {'name': 'የዓለም\nዋንጫ', 'id': '1'},
];

List<String> shortLeagueNames = [
  DemoLocalizations.all,
  'ፕሪምየር ሊግ',
  'ሻምፒዮንስ ሊግ',
  'የኢትዮጵያ ፕሪምየር ሊግ',
  'ላሊጋ',
  'ሊግ 1',
  'ሴሪያ',
  'ቡንደስ ሊጋ',
  'የአውሮፓ ሊግ',
  'የሳዑዲ ፕሮ ሊግ',
  'ኤፍ ኤ ካፕ',
  'ካራባኦ EFL',
];

List<String> leaguePics = [
  'english',
  'uefa',
  'eth_league',
  'laliga',
  'league1',
  'seria',
  'bundes',
  'europa',
  'pro_league',
  'fa',
  'carabao',
  'efl_league_one',
  'efl_league_two',
  'efl_championsship',
  'turk',
  'egypt',
  'premier_soccer_league', //southafrica
  'MajorLeagueSoccer(MLS)',
  'netherland',
  'belgium',
  'Qatar',
  'premiera', //portugal
  'premiership', //scotland
  'africa',
  'europe',
  'nations_league',
  'CopaAmerica',
  'olympic',
  'fifa',
  'fifa',
  'fifa',
  'fifa',
  'fifa',
  'fifa'
];

List<int> leagueids = [
  39,
  2,
  363,
  140,
  61,
  135,
  78,
  3,
  307,
  45,
  48,
  41,
  42,
  40,
  203,
  233,
  288,
  253,
  88,
  144,
  305,
  94,
  179,
  6,
  4,
  5,
  9,
  480,
  32,
  29,
  34,
  31,
  30,
  33,
];
List<IconData> icons = [
  Icons.home,
  Icons.explore,
  Icons.search,
  Icons.feed,
  Icons.post_add,
  Icons.local_activity,
  Icons.settings,
  Icons.person
];
List<int> leagueidsForMatches = [
  0,
  39,
  2,
  363,
  140,
  61,
  135,
  78,
  3,
  307,
  45,
  48,
  41,
  42,
  40,
  203,
  233,
  288,
  253,
  88,
  144,
  305,
  94,
  179,
  6,
  4,
  5,
  9,
  480,
  32,
  29,
  34,
  31,
  30,
  33,
];
String content = 'standing';
